### ISSUE TITLE
Routes URL not Accessable

### ISSUE THREAD

**Issue by zakrian07** [OtterClam/otter-frontend#23]
Hello,
We have successfully added the contracts and but on otter-frontend main branch
we are unable to access the stake and dashboards URL
is there any clear documentation for it? the inner routes are accessible with other branches
but having issue in the main branch 
any help would be appreciated

**Comment by otterclamking** [comment]
Here is the setup guide https://github.com/OtterClam/otter-frontend#run-the-app
